name: Build for Android
on: [push,pull_request]

jobs:
  build-connected:
    name: Build Connected
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Connected
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer-c
        with:
          workdir: Connected
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-connected
          path: ${{ steps.buildozer-c.outputs.filename }}
          
  build-hypertiledash:
    name: Build hypertiledash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Hypertiledash
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer-h
        with:
          workdir: HyperTile Dash
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-hypertiledash
          path: ${{ steps.buildozer-h.outputs.filename }}                    
